server {
    listen 80;
    server_name {{ dominio }} www.{{ dominio }};
    client_max_body_size 50M;

    root /home/{{ conta }}/project/dist/;
    index index.html index.htm;

    access_log /home/{{ conta }}/logs/access.log;
    error_log /home/{{ conta }}/logs/error.log;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location ~ /\. {
        deny all;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
